#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

set -x

cat > "${ROOTDIR}/AUTHORS" <<- EOF
<<<<<<< HEAD
	#File @generated by generate_authors.sh. DO NOT EDIT
=======
	#File @generated by generate_authors.sh DO NOT EDIT
>>>>>>> b7f14ce1bcb9ef2e3905db8ab9b7617a7236f43f
	#This file lists all contributors to the repository
	#See generate_authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%N <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
